_target_: lightning.pytorch.trainer.Trainer

# Disable sanity check at the beginning of training.
num_sanity_val_steps: 0

default_root_dir: ${paths.output_dir}

max_epochs: -1

accelerator: gpu
devices: [0]

log_every_n_steps: 10

# Changed from 16-mixed
precision: bf16-mixed

check_val_every_n_epoch: 5

# Protects against spikes in learning. Keeps the model weights from jumping too wildly.
gradient_clip_val: 4

# Set it to 2 or 4 for small GPUs that cannot fit large batches in memory
accumulate_grad_batches: 1
