_target_: lightning.pytorch.trainer.Trainer

# Disable sanity check at the beginning of training.
num_sanity_val_steps: 0

default_root_dir: ${paths.output_dir}

max_epochs: -1

accelerator: gpu
devices: [0]

log_every_n_steps: 10

# Changed from 16-mixed
precision: 16-mixed

# perform a validation loop every N training epochs
check_val_every_n_epoch: 4

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# Protects against spikes in learning. Keeps the model weights from jumping too wildly.
gradient_clip_val: 5