_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

max_epochs: 4000

accelerator: gpu
devices: [0]

# log more frequently than the number of batches per epoch
log_every_n_steps: 5

# mixed precision for better speed (changed from 16-mixed)
precision: bf16-mixed

# perform a validation loop every N training epochs
check_val_every_n_epoch: 5

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

gradient_clip_val: 5.0
