defaults:
  - _self_
  - encoder: default.yaml
  - decoder: default.yaml
  - cfm: default.yaml
  - optimizer: adamw.yaml

_target_: matcha.models.matcha_tts.MatchaTTS
n_vocab: 156

n_spks: ${data.n_spks}
spk_emb_dim: 96
n_feats: ${data.n_feats}
data_statistics: ${data.data_statistics}
prior_loss: true
use_precomputed_durations: ${data.load_durations}
