# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.TQDMProgressBar.html
# Alternative to RichProgressBar with much lower computational overhead

tqdm_progress_bar:
  _target_: lightning.pytorch.callbacks.TQDMProgressBar
  refresh_rate: 3  # Refresh every N batches

